### ISSUE TITLE
Gimlet Sequencer strangeness

### ISSUE THREAD

**Issue by Aaron-Hartwig** [oxidecomputer/quartz#242]
As observed on https://github.com/oxidecomputer/mfg-troubleshooting/issues/47.

FPGA register dumps ([map](https://buildomat.eng.oxide.computer/wg/0/artefact/01JCRYHE964SY2S5J8KYZCF61G/3oqhr4L4LhUZr6SkBc4WrVsOiJNQwRXoqbFueh4tVPSeU21t/01JCRYHVM6AWRWX3DN1QHWE0H3/01JCS0FCJ58DWG6MX82TJ5RS5R/gimlet_regs.html))
Whilst in A2
```
aaron@camilla ~ $  pfexec humility -p 0483:3754:003D00174741500820383733 -a /data/local/images/gimlet/f/sp/build-gimlet-f-lab-image-default-v1.0.7.zip spi --nbytes 64 -p 2 -w 0x1,0x0,0x0 -r --discard 3
humility: attached to 0483:3754:003D00174741500820383733 via ST-Link V3
humility: SPI master is spi2_driver
             \/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 01 de 00 00 00 d7 b4 6d 04 8c 2d 58 cd fc 00 00 | .......m..-X....
0x00000010 | 00 01 06 00 01 00 00 00 05 00 00 0b 00 ff 05 00 | ................
0x00000020 | 00 ff 03 ff 00 10 00 00 00 35 ff ff 00 ff 00 00 | .........5......
0x00000030 | 00 00 00 00 00 00 ff ff ff ff ff ff ff          | .............
```

Whilst in A0
```
aaron@camilla ~ $  pfexec humility -p 0483:3754:003D00174741500820383733 -a /data/local/images/gimlet/f/sp/build-gimlet-f-lab-image-default-v1.0.7.zip spi --nbytes 64 -p 2 -w 0x1,0x0,0x0 -r --discard 3
humility: attached to 0483:3754:003D00174741500820383733 via ST-Link V3
humility: SPI master is spi2_driver
             \/  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0x00000000 | 01 de 00 00 00 d7 b4 6d 04 8c 2d 58 cd fc 00 00 | .......m..-X....
0x00000010 | 00 0d 06 02 01 00 0c 04 05 00 0f 04 ff ff 05 03 | ................
0x00000020 | 7f ff 04 ff 00 0f ff 00 7f 37 ff ff 00 ff 00 00 | .........7......
0x00000030 | 0c ff 03 00 00 00 ff ff ff ff ff ff ff          | .............
```

There is definitely an SP bug here too (https://github.com/oxidecomputer/hubris/issues/1929), but we don't think it is the root cause. The problematic unit in the troubleshooting issue referenced above would seem to have an actual A1 problem and the sequencer is not reacting to it appropriately.

**Comment by nathanaelhuffman** [comment]
The code in question is here: https://github.com/oxidecomputer/quartz/blob/fb77d29f9571f682810a8bbea41029a6d4298c1c/hdl/projects/gimlet/sequencer/A1Block.bsv#L178

This is certainly not the most elegant way of handling this but I put the error handling in the IDLE state such that the state transitions back to IDLE but won't actually disable the rails until the downstream rails are idle also.  While a bit confusing when we looked into this, I think it is safe behavior.  A different, and probably better way of handling this would be to transition to a new state that waits for downstream idle on any errors that occur once the state machine has started.  I'm currently inclined to leave this as-is unless we have other reasons to change the sequencer logic for another reason.

And none of this is related to the actual board-level failure that we're still troubleshooting.
